# Generated by Django 6.0.7 on 2026-07-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_skill_options_skill_category_skill_proficiency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
    ]
