# Generated by Django 6.0.7 on 2026-07-29 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_alter_skill_options_remove_skill_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-proficiency']},
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('tool', 'Tool')], default='language', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
